server:
  port: 9000

authorization:
  bcryptPrefix: "{bcrypt}"
  token:
    header:
      name: Authorization
      prefix: "Bearer "
    secret: t3pCSx2wx1ExbQ5z43XXB8my/KR24aon4EH/niU9iZi1I3S69rk1QhlMFFsTrZIY
    expirationTime: 3600000
  refresh-token:
    expirationTime: 86400000


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6000/ks
    username: ks_user
    password: sigurnost
    #JPA properties

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          timezone: UTC
    open-in-view: false

  flyway:
    baseline-on-migrate: true
  jackson:
    serialization:
      fail_on_empty_beans: false
  servlet:
    multipart:
      max-file-size: 5MB
